cvapp/cvapp/urls.py
from django.contrib import admin
from django.urls import path
from cv import views

urlpatterns = [
    path('', views.home_view, name = "home"),
    path('profile/', views.get_data, name = "profile"),
    path('tech/', views.get_tech, name = "tech"),
    path('skills/', views.get_skills, name = "skills"),
    path('work/', views.get_work, name = "work"),
    path('education/', views.get_education, name = "education"),
    path('language/', views.get_language, name = "language"),
    path('template/', views.get_template, name = "template"),
    path('template1/', views.template1_view, name = "template1"),
    path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),
    path('admin/', admin.site.urls),
]

cvapp/cv/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
SKILLS_CHOICES1 = (
    ("1", "Communication"), 
    ("2", "Teamwork"), 
    ("3", "Innovation"), 
    ("4", "Leadership"), 
    ("5", "Motivation"))

SKILLS_CHOICES2 = (
    ("1", "Problem-solving"),
    ("2", "Organisation"),
    ("3", "Perseverance"),
    ("4", "Ability to work under pressure"),
    ("5","Adaptability"))  

SKILLS_CHOICES3 = (
    ("1", "Work Ethic"), 
    ("2", "Flexibility"), 
    ("3", "Time Management"), 
    ("4", "Critical Thinking"), 
    ("5", "Creativity"))

TEMPLATE_CHOICES = (
    ("", "Choose.."),
    ("1", "Template 1"))

LANGUAGE_CHOICES1 = (
    ("", "Choose.."),
    ("1", "English"), 
    ("2", "French"), 
    ("3", "Spanish"), 
    ("4", "German"), 
    ("5", "Italian"))


class Data(models.Model):
    firstname    = models.CharField(max_length=50)
    lastname     = models.CharField(max_length=50)
    email        = models.EmailField()
    phone        = models.IntegerField()

    def __str__(self):
        return '{0} {1}' .format(self.firstname, self.lastname)
    


class Tech(models.Model):
    profile      = models.CharField(max_length=300)
    tech1        = models.CharField(max_length=50)
    tech2        = models.CharField(max_length=50, blank=True, null = True)
    tech3        = models.CharField(max_length=50, blank=True, null = True)
    data         = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return '{0}, {1}, {2}' .format(self.tech1, self.tech2, self.tech3)


class Skill(models.Model):
    skills1      = models.CharField(max_length=1, choices=SKILLS_CHOICES1)
    skills2      = models.CharField(max_length=1, choices=SKILLS_CHOICES2)
    skills3      = models.CharField(max_length=1, choices=SKILLS_CHOICES3)
    data         = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

class Language(models.Model):
    language1        = models.CharField(max_length=50)
    language2        = models.CharField(max_length=50, blank=True, null = True)
    language3        = models.CharField(max_length=50, blank=True, null = True)
    data             = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return '{0}, {1}, {2}' .format(self.language1, self.language2, self.language3)


class Work(models.Model):
    position     = models.CharField(max_length=50)
    company      = models.CharField(max_length=50)
    description  = models.CharField(max_length=250)
    data         = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return '{0}, {1}' .format(self.position, self.company)


class Education(models.Model):
    institution  = models.CharField(max_length=50)
    studies      = models.CharField(max_length=50)
    description  = models.CharField(max_length=250)
    data         = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return '{0}, {1}' .format(self.institution, self.studies)

class Template(models.Model):
    type         = models.CharField(max_length=1, choices=TEMPLATE_CHOICES)
    data         = models.OneToOneField('Data', on_delete=models.CASCADE, blank=True, null = True)

cvapp/cv/forms.py
from django import forms
from .models import Data, Skill, Work, Education, Template, Language, Tech


class FormData(forms.ModelForm):
    class Meta:
        model    = Data
        fields   = ['firstname', 'lastname', 'email', 'phone']
   

class FormTech(forms.ModelForm):
    class Meta:
        model    = Tech
        fields = ['profile', 'tech1', 'tech2', 'tech3']


class FormSkill(forms.ModelForm):
    class Meta:
        model    = Skill
        fields   = ['skills1', 'skills2', 'skills3']


class FormWork(forms.ModelForm):
    class Meta:
        model    = Work
        fields   = ['position', 'company', 'description']


class FormEducation(forms.ModelForm):
    class Meta:
        model    = Education
        fields   = ['institution', 'studies', 'description']


class FormLanguage(forms.ModelForm):
    class Meta:
        model    = Language
        fields   = ['language1', 'language2', 'language3']


class FormTemplate(forms.ModelForm):
    class Meta:
        model    = Template
        fields   = ['type']

cvapp/cv/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import FormData, FormEducation, FormLanguage, FormSkill, FormTech, FormTemplate, FormWork
from .models import Data, Skill, Education, Work, Language, Tech
from io import BytesIO
from django.views import View
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa



def home_view(request):
    return render(request, "home.html", {})

def get_data(request):
    if request.method == 'POST':
        form = FormData(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tech')
    else:
        form = FormData()

    return render(request, 'profile.html', {'form': form})


def get_tech(request):
    if request.method == 'POST':
        form = FormTech(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/skills')
    else:
        form = FormTech()

    return render(request, 'profile.html', {'form': form})

def get_skills(request):
    if request.method == 'POST':
        form = FormSkill(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/work')

    else:
        form = FormSkill()

    return render(request, 'skills.html', {'form': form})

def get_work(request):
    if request.method == 'POST':
        form = FormWork(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/education')

    else:
        form = FormWork()

    return render(request, 'work.html', {'form': form})

def get_education(request):
    if request.method == 'POST':
        form = FormEducation(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/language')

    else:
        form = FormEducation()

    return render(request, 'education.html', {'form': form})

def get_language(request):
    if request.method == 'POST':
        form = FormLanguage(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/template')

    else:
        form = FormLanguage()

    return render(request, 'language.html', {'form': form})

def get_template(request):
    if request.method == 'POST':
        form = FormTemplate(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/template1')

    else:
        form = FormTemplate()

    return render(request, 'template.html', {'form': form})

def template1_view(request):
    data = Data.objects.last()
    tech = Tech.objects.last()
    skill = Skill.objects.last()
    education = Education.objects.last()
    work = Work.objects.last()
    language = Language.objects.last()
    return render(request, "template1.html", {'data': data, 'tech': tech, 'skill': skill, 'education': education, 'work': work, 'language': language})

data = Data.objects.last()
tech = Tech.objects.last()
skill = Skill.objects.last()
education = Education.objects.last()
work = Work.objects.last()
language = Language.objects.last()
datas = {'data': data, 'tech': tech, 'skill': skill, 'education': education, 'work': work, 'language': language}

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

class DownloadPDF(View):
    def get(self, request, *args, **kwargs):
        pdf = render_to_pdf('template1.html', datas)
        response = HttpResponse(pdf, content_type='application/pdf')
        filename = "Invoice_%s.pdf" %("12341231")
        content = "attachment; filename='%s'" %(filename)
        response['Content-Disposition'] = content
        return response

cvapp/cv/templates/education.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span"> Last Education</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Next</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="panel">
            <div class="left">
                <span class="title">Build your CV with us!</span>
                <button class="button-left" onclick="location.href = '/profile'">Next</button>
            </div>
            <div class="right">
                {% load static %}
                <img src="{% static 'images/1.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/language.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span"> Languages</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Next</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/profile.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span">Personal Details</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Next</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/skills.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span">Top three strenghts</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Next</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/template.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span">Template</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Generate</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>

cvapp/cv/templates/template1.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<title>CV</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="all" /> 
	  {% load static %}
    <link rel="stylesheet" href="{% static 'css/resume.css' %}">
</head>
<body>

<div id="doc2" class="yui-t7">
	<a class="btn btn-info"  href="{% url 'pdf_download' %}">Download PDF</a>
	<div id="inner">
		<div id="hd">
			<div class="yui-gc">
				<div class="yui-u first">
					<h1>{{data.firstname}}{{' '}}{{ data.lastname}}</h1>
				</div>
                <div class="yui-u">
					<div class="contact-info">
						<h3>{{data.email}}</h3>
						<h3>{{data.phone}}</h3>
					</div>
				</div>
			</div>
		</div>

		<div id="bd">
			<div id="yui-main">
				<div class="yui-b">
					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Profile</h2>
						</div>
						<div class="yui-u">
							<p class="enlarge">{{tech.profile}}</p>
						</div>
					</div>

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Strenghts</h2>
						</div>
						<div class="yui-u">
							<ul class="talent">
								<li class="last">{{skill.get_skills1_display}}</li>
							</ul>

							<ul class="talent">
								<li class="last">{{skill.get_skills2_display}}</li>
							</ul>

							<ul class="talent">
								<li class="last">{{skill.get_skills3_display}}</li>
							</ul>
						</div>
					</div>

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Technical</h2>
						</div>
						<div class="yui-u">
							<ul class="talent">
								<li class="last">{{tech.tech1}}</li>
							</ul>

							<ul class="talent">
								<li class="last">{% if tech.tech2 %} {{tech.tech2}} {% else %} &nbsp; {% endif %}</li>
							</ul>

							<ul class="talent">
								<li class="last">{% if tech.tech3 %} {{tech.tech3}} {% else %} &nbsp; {% endif %}</li>
							</ul>
						</div>
					</div>

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Experience</h2>
						</div>

						<div class="yui-u">
							<div class="job last">
								<h2>{{work.company}}</h2>
								<h3>{{work.position}}</h3>
								<p>{{work.description}}</p>
							</div>   
						</div>
					</div>


					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Education</h2>
						</div>
						<div class="yui-u">
							<h2>{{education.institution}}</h2>
							<h3>{{education.studies}}</h3>
							<p>{{education.description}} </p>
						</div>
					</div>

					<div class="yui-gf last">
						<div class="yui-u first">
							<h2>Languages</h2>
						</div>
						<div class="yui-u">
							<ul class="talent">
								<li class="last">{{language.language1}}</li>
							</ul>

							<ul class="talent">
								<li class="last">{% if language.language2 %} {{language.language2}} {% else %} &nbsp; {% endif %}</li>
							</ul>

							<ul class="talent">
								<li class="last">{% if language.language3 %} {{language.language3}} {% else %} &nbsp; {% endif %}</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

cvapp/cv/templates/work.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    </head>
    </head>
    <body>
        <div class="panel">
            <div class="right">
                <div class="title">
                    <span class="title-span"> Last Work Experince</span>
                </div>
                <div class="info">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{form|crispy }}
                    <button type="submit" class="btn btn-default">Next</button>
                </form>
                </div>
            </div>
            <div class="left">
                {% load static %}
                <img src="{% static 'images/4.png' %}" alt="image" class="image-right">
            </div>
        </div>
    </body>
</html>